"""Initial migration

Revision ID: 737ab0bc941b
Revises: 8e4c33fd2c00
Create Date: 2024-06-04 19:47:40.116862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '737ab0bc941b'
down_revision = '8e4c33fd2c00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.alter_column('cover',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.alter_column('cover',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
