"""Initial migration

Revision ID: 8042dd93d857
Revises: 737ab0bc941b
Create Date: 2024-06-04 23:05:59.278777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8042dd93d857'
down_revision = '737ab0bc941b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_downloads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_downloads', schema=None) as batch_op:
        batch_op.drop_column('author')

    # ### end Alembic commands ###
